# Generated by Django 3.0 on 2020-01-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_album_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
