# Generated by Django 3.0 on 2020-01-05 16:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_song_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='pic',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
