# Generated by Django 3.0 on 2020-01-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_auto_20200105_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='time',
            field=models.DateTimeField(verbose_name='timezone.now'),
        ),
    ]
