# Generated by Django 3.0 on 2020-01-06 11:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_auto_20200105_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audio',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
